### ISSUE TITLE
Use version from annotated tag

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-auto-version#1]
There are teams that prefer to cut release "on demand", rather than with every change on master (example: [linkedin/li-apache-kafka-clients](https://github.com/linkedin/li-apache-kafka-clients/blob/master/build.gradle#L187), [mockito-kotlin](http://github.com/mockito/mockito-kotlin)). Those teams are not supported cleanly by our plugin.

**Problem statement**: how do we enable teams to *release on demand* and provide [automated changelog](https://github.com/shipkit/shipkit-changelog)?

❓ Options
 - a) keep shipkit-auto-version simple, let other plugins solve this use case. **Problem**: [allegro/axion-release-plugin](https://github.com/allegro/axion-release-plugin) does not expose *previous version* information cleanly and it is necessary for automated changelog.
 - b) enhance shipkit-auto-version to support picking the version directly from annotated tag.

💡Solution discussion:
 - a) is preferred to keep shipkit-auto-version laser focused and reduce future maintenance. However, I was not able to [cleanly enhance axion plugin](https://github.com/allegro/axion-release-plugin/pull/397) to expose *previous version* information.
 - b) can be designed as a simple enhancement to shipkit-auto-version ⬇️

🌱  Implementation overview:
 - missing `version.properties` file or missing `version` property **is allowed** and signals *simplified* behavior of our plugin (currently, the file and property are *required*).
 - our plugin deducts current version this way:
    - if we checked out a tag (`git checkout 1.2.3`), pick that version: `1.2.3`
      - To find out if git repo is checked out to a tag, we can run `git describe --tags`
    - if we checkout out a branch (`git checkout main`), pick the highest tag
    - no counting commits logic is necessary in this *simplified* behavior

🌎 Long term goals:
 - should we deprecate functionality ⬆️ when axion plugin supports [previous version information](https://github.com/allegro/axion-release-plugin/pull/397)? **No.** Shipkit-auto-version will continue to support the basic use case described in this ticket. We endorse axion plugin for complex use cases not supported out of the box by shipkit-auto-version. However, we encourage build experts to keep their automation simple ([KISS](https://en.wikipedia.org/wiki/KISS_principle) 💋).

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at it?

**Comment by shestee** [comment]
Thank you for asking. I'll check this out.

**Comment by nipafx** [comment]
Just a note:

> * missing `version.properties` file or missing `version` property is allowed and signals simplified behavior of our plugin

When I experimented with #72 I explored passing the project version via command line, which also makes `version.properties` superfluous, I discovered that the file is required nonetheless. This seems to contradict [the docs](https://github.com/shipkit/shipkit-auto-version#implementation-details), which say:

> * if the gradle project already has a set version (e.g. from the command line), use that version
> * if no file or wrong format fail

**Comment by mockitoguy** [comment]
@nipafx, I clarified that in the description (we're changing this behavior). Thx!
