### ISSUE TITLE
Support Windows platform

### ISSUE THREAD

**Issue by Sh4tterh4nd** [shipkit/shipkit-auto-version#10]
On Windows using "[Git for Windows](https://git-scm.com/download/win)" we only get:
  - reason: shipkit-auto-version found no tags
(with tags existing and beeing in the right pattern "v1.0.1"

I have debuged it allready a bit, the issue lies with using `.split(System.lineSeparator())` (AutoVersioning.class line 62 and CommitCounter.java line 45)

It seems that git for windows doesn't use Windows's new Line and thus "System.lineSeperator" doesn't work.

A fix would be instead of using System.lineSeperator use the regular expression "\R", which is [supported since Java 8 ](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html)

> Linebreak matcher
>\R | Any Unicode linebreak sequence, is equivalent to \u000D\u000A\|[\u000A\u000B\u000C\u000D\u0085\u2028\u2029]

**Comment by mockitoguy** [comment]
Sounds like a great idea? Do you want to submit a PR? The plugin is really small so I hope it is easy to fix. Thanks for reporting!!!

**Comment by mockitoguy** [comment]
Hey @Sh4tterh4nd, thank you for your PR!

Do you mind contributing an update to our GH Actions so that we also run the build on windows? Thanks!
