### ISSUE TITLE
Support versions in `\\d+\\.\\d+\\.\\d+\\.\\*` format

### ISSUE THREAD

**Issue by ljfgem** [shipkit/shipkit-auto-version#109]
Hi, we are trying to use this plugin for [linkedin/iceberg](https://github.com/linkedin/iceberg/tree/li-0.11.x), but it doesn't support the version format of `0.11.1.*`. Given `\\d+\\.\\d+\\.\\d+\\.\\*` version format is also common, could it be supported? Thanks!

**Comment by mockitoguy** [comment]
Yes, it shouldn't be too much work. How urgent it is?

**Comment by ljfgem** [comment]
Thanks for your quick reply! It would be great if we can use such a format by early next week.

**Comment by mockitoguy** [comment]
Hey @ljfgem, do you still need this feature? I have a PR out (#111) but wanted to test e2e on iceberg. However, iceberg does not build for me when I clone your main dev branch:

```
* What went wrong:
A problem occurred configuring root project 'iceberg'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.palantir.baseline:gradle-junit-reports:0.55.0.
     Required by:
         project : > com.palantir.baseline:gradle-baseline-java:0.55.0
      > Could not resolve com.palantir.baseline:gradle-junit-reports:0.55.0.
         > Could not get resource 'http://palantir.bintray.com/releases/com/palantir/baseline/gradle-junit-reports/0.55.0/gradle-junit-reports-0.55.0.pom'.
            > Could not GET 'http://palantir.bintray.com/releases/com/palantir/baseline/gradle-junit-reports/0.55.0/gradle-junit-reports-0.55.0.pom'. Received status code 502 from server: Bad Gateway
```

**Comment by ljfgem** [comment]
Hi @mockitoguy, thanks for your help! Yeah we still need this feature.
As for the plugin not found issue, I think you may refer to [this commit](https://github.com/linkedin/iceberg/pull/101/commits/0035f578c54ebbf7300e189d5ff4d6df45474a5a), in which I moved `maven { url "https://plugins.gradle.org/m2/" }` to be the first one to solve this issue.
And we are using `li-0.11.x` branch, feel free to review https://github.com/linkedin/iceberg/pull/101 that I opened to use shipkit for auto release.

cc: @wmoustafa

**Comment by mockitoguy** [comment]
Hey @ljfgem, this should work now, can you try? Let us know if there are any problems.

**Comment by ljfgem** [comment]
Thanks you so much @mockitoguy, it's working well now.
