### ISSUE TITLE
Minor but confusing typo?

### ISSUE THREAD

**Issue by logantracyo** [shipkit/shipkit-auto-version#115]
It appears that `deducted` ("subtract or take away (an amount or part) from a total") is being used in several spots in place of `deduced` ("arrive at (a fact or a conclusion) by reasoning; draw as a logical conclusion") -- but maybe I'm misunderstanding what's meant (rather than just being nit-picky!?)

Shall I submit a PR?  Or just apologize? :)

**Comment by koral--** [comment]
Feel free to submit a PR.

**Comment by logantracyo** [comment]
Just one more (non-code) change is needed -- the About section on the home page:

> Gradle plugin that helps automating releases by automatically **~~deducting~~ deducing** the next Semver version

**Comment by koral--** [comment]
Thanks, I've just changed that.
