### ISSUE TITLE
Are the tests maintained on this project?

### ISSUE THREAD

**Issue by benbitrise** [shipkit/shipkit-auto-version#182]
I'm in the process of opening a PR for this project (related to adding support for Gradle's configuration cache) and ./gradlew test does not execute anything. 

Based on my research the Spock framework doesn't support Junit 4 anymore. But I see 4 being specified in the build.gradle. 

Also, the README says to use the contributing guide for the shipkit-changelog project, [which simply recommends](https://github.com/shipkit/shipkit-changelog?tab=readme-ov-file#testing) manual testing.

These lead me to believe the tests are no longer maintained and I shouldn't worry about them for my PR. Accurate?

**Comment by koral--** [comment]
It was not intended that gradle did not execute tests. I've just fixed that.
Thanks for the report.

**Comment by benbitrise** [comment]
Awesome. Thanks!
