### ISSUE TITLE
Support SNAPSHOT versions and/or manual override version

### ISSUE THREAD

**Issue by jplaisted** [shipkit/shipkit-auto-version#37]
It is useful, to me, that when building things locally it has some clear version that is never published to a repo like maven central or bintray (i.e. ends with `-SNAPSHOT`).

The current workflow with this plugin can be a little confusing. What happens if I check out a repo at version X, do some work, and at some point the repo publishes version X+1. If I then build mine locally and publish locally, I'm also at X+1. Which one will win? The published version or local version? I believe the answer is the local, but then what happens if I want to use the published version later? It'd be useful to build mine in away that won't ever conflict with a published version.

I'm thinking if the user specified `-Pversion=x` on the gradle CLI that the plugin should accept it as an override. Or, there could be a more specific `-Psnapshot` flag to enable adding a `-SNAPSHOT` suffix, which is less flexible. Though I understand sometimes `SNAPSHOT` versions _are_ published, though that isn't my personal development flow...

Happy to submit a PR if we can work out the semantics and accept the issue.

**Comment by mockitoguy** [comment]
> Happy to submit a PR if we can work out the semantics and accept the issue.

Awesome, let's discuss the semantics. My initial instinct on how to solve it is to make the auto-version-plugin _respect_ the version supplied by the user. Effectively, the plugin should check if "project.version" is already specified. If so, we _just use_ that version, printing a clean explanation why we are using it. This approach would enable a scenario like: ```./gradlew build -Pversion=1.0.0-SNAPSHOT```.

**Comment by jplaisted** [comment]
I agree, I had the same thought in the OP even if it was little less clear.

This seems simple enough. We can test to see if a version has already been set by testing if `project.getVersion().equals(Project.DEFAULT_VERSION)`.

Testing this out, we also need to set the shipkit previous version, as things may be looking for that (e.g. `shipkit-changelog`'s `generateChangelog` task). We can't just skip the entire plugin. I assume we should just leave this as is.

**Comment by jplaisted** [comment]
Thanks! See it in action:

https://github.com/linkedin/datahub-gma/pull/52
