### ISSUE TITLE
Conveniently provide previous version information

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-auto-version#52]
Currently the previous version is provided using the following property: ```project.ext.'shipkit-auto-version.previous-version'``` ([code link](https://github.com/shipkit/shipkit-auto-version/blob/master/src/main/java/org/shipkit/auto/version/AutoVersionPlugin.java#L14)). A property like that is not convenient because it yields additional complexity (string concat + conditional complexity). Here's an example when using [changelog plugin](https://github.com/shipkit/shipkit-changelog):

```Gradle
tasks.named("generateChangelog") {   
    previousRevision = project.ext.'shipkit-auto-version.previous-version' ? 'v' + project.ext.'shipkit-auto-version.previous-version' : null
    //...
```

Proposed solution is to expose another property: ```project.ext.'shipkit-auto-version.previous-tag'```:

```Gradle
tasks.named("generateChangelog") {   
    previousRevision = project.ext.'shipkit-auto-version.previous-tag'
    //...
```

Related to https://github.com/shipkit/shipkit-changelog/issues/45

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at it?

**Comment by shestee** [comment]
> @shestee, do you want to take a stab at it?

Yes, sure. I'll take a look at this.
