### ISSUE TITLE
Start using new 'previous-tag' property

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-auto-version#55]
Let's start using new 'previous-tag' property in a) build files (see release.gradle)  b) documentation (see README.md)

We should do it in all clients that currently use shipkit-auto-version. See the client list in README.md. We can do it one PR at a time ;-)

**Comment by shestee** [comment]
Ok, I will do it starting from Shipkit Auto Version.

**Comment by mockitoguy** [comment]
I believe we are don. Please reopen if needed!
