### ISSUE TITLE
Use -SNAPSHOT version when not building from tag

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-auto-version#77]
I was trying to use the new functionality in Mockito and I found that we can improve the current behavior so that it's easier to set up automated releases.

When *building* from tag (example: when `git describe --tags` yields `1.0.0`), then the plugin correctly picks `1.0.0`. No change needed here.

When *not* building from tag (example: when `git describe --tags` yields `1.0.0-3-gd90ced6`), then:
- the current behavior is to pick version `1.0.0`
- it's better to pick next snapshot, e.g. `1.0.1-SNAPSHOT` (we should pick the next patch version, regardless of the amount of commits on top of the tag).

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at this enhancement?

**Comment by shestee** [comment]
@mockitoguy, thank you for asking, I'll do it

**Comment by mockitoguy** [comment]
Thanks!
