### ISSUE TITLE
Bug in error reporting

### ISSUE THREAD

**Issue by mockitoguy** [shipkit/shipkit-auto-version#82]
It seems that there is a bug related to exception handling. We are not checking the presence of the optional [here](https://github.com/shipkit/shipkit-auto-version/blob/04d9944424ed3f8e2fae4615032f47fa2da90a69/src/main/java/org/shipkit/auto/version/AutoVersion.java#L67). This causes build failures such as [those](https://github.com/mockito/mockito-kotlin/pull/435/checks?check_run_id=2623270165).

**Comment by mockitoguy** [comment]
@shestee, do you want to take a stab at it?

**Comment by shestee** [comment]
Yes, I'll take a look at this.
